### ISSUE TITLE
Questions about positions input and equirectangular image

### ISSUE THREAD

**Issue by MarSaKi** [google-research/pathdreamer#6]
Thanks for your great work! I believe this work could promote the developments of model-based methods for VLN!
May I ask some questions?
1.Predicting a further panorama needs the positions and orientations of the agent, but I note in you [demo,](https://github.com/google-research/pathdreamer/blob/master/Pathdreamer_Example_Colab.ipynb) only the positions are input to the model. How is it work? The agent implicitly calculates the orientations?
2. How to get the equirectangular image in the Matterport3D Simulator (the simulator is based on a skybox image for each viewpoint). Do you have any scripts?

**Comment by kohjingyu** [comment]
Thanks for your interest in our work! To answer your questions:

1) We assume a default orientation (see https://github.com/google-research/pathdreamer/blob/master/models/pathdreamer_models.py#L207-L211)
2) The official Matterport3D dataset (not the simulator) contains 10,800 high resolution panoramas which we use to train on. Please visit their [website](https://niessner.github.io/Matterport/) for download instructions.

**Comment by MarSaKi** [comment]
Thanks for your reply, it's very useful. Great work!

I still have a question:
![image](https://user-images.githubusercontent.com/24617881/149122442-1af5f6b8-d8a4-4ac8-b76d-68da68f82a8b.png)

In the VLN validation experiment of your paper (Sec.4.2.). How did you encode the path of Pathdreamer model? As far as I know, the visual path encoder of [On the Evaluation of Vision-and-Language Navigation Instructions](https://arxiv.org/pdf/2101.10504.pdf) is based on a navigable view from **36 discrete views** (**Discrete Panorama**), which is slightly different from the output of pathdreamer  (**Continuous Panorama**). 

Did you use different visual **path encoders** for 'Pathdreamer' and 'Ground Truth' settings?  Or manually discretize the output panorama of Pathdreamer model? Could you please give more details of the VLN validation experiments, thanks! 

Cheers!

**Comment by kohjingyu** [comment]
Hi,

Sorry for the late response.

1) We sample 36 discrete perspective views from our generated equirectangular image, similar to how [R2R](https://github.com/peteanderson80/Matterport3DSimulator/blob/master/scripts/precompute_img_features.py) does.
2) We use the same path encoder for both groundtruth and Pathdreamer. Our VLN experiment runs off models from [VALAN](https://github.com/google-research/valan) (but it is likely that you can achieve similar uplift in success rate by using planning for any VLN agent). Unfortunately our code for this part is a bit messy and will likely not be released.

Hope that helps!

**Comment by MarSaKi** [comment]
Thanks for your reply! It's very useful!

Best Regards!
